language: ruby
branches:
  only:
    - master
env:
  global:
    - JRUBY_OPTS="$JRUBY_OPTS --debug"
  matrix:
    - RAILS_VERSION="~> 4.2.0"
    - RAILS_VERSION="~> 5.0.0"
    - RAILS_VERSION="~> 5.1.0"
    - RAILS_VERSION="edge"
rvm:
  - 2.1.10
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - jruby-9.1.8.0
  - jruby-head
  - rbx-2
  - ruby-head
jdk: oraclejdk8
matrix:
  allow_failures:
    - rvm: jruby-head
    - rvm: rbx-2
    - rvm: ruby-head
    - env: RAILS_VERSION="edge"
    - rvm: jruby-9.1.8.0
      env: RAILS_VERSION="~> 5.1.0"
  fast_finish: true
  # legacy testing
  # things still run and we don't have a good reason to break it
  # but we don't need to keep running the full matrix
  include:
    - rvm: 2.3.4
      env: RAILS_VERSION="~> 3.0.0"
    - rvm: 2.3.4
      env: RAILS_VERSION="~> 3.1.0"
    - rvm: 2.3.4
      env: RAILS_VERSION="~> 3.2.0"
    - rvm: 2.3.4
      env: RAILS_VERSION="~> 4.0.0"
    - rvm: 2.3.4
      env: RAILS_VERSION="~> 4.1.0"
  exclude:
    - rvm: 2.1.10
      env: RAILS_VERSION="~> 5.0.0"
    - rvm: 2.1.10
      env: RAILS_VERSION="~> 5.1.0"
    - rvm: 2.1.10
      env: RAILS_VERSION="edge"
sudo: false
